create extension if not exists pgcrypto;
create table if not exists public.products(id bigint primary key,name text not null,slug text unique not null,price numeric(12,2) not null,use_text text,benefit text,for_who text,available boolean default true,stock integer default 0,image_url text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.categories(id uuid primary key default gen_random_uuid(),name text unique not null,slug text unique not null,tagline text,banner_url text,created_at timestamptz default now());
create table if not exists public.category_products(category_id uuid references public.categories(id) on delete cascade,product_id bigint references public.products(id) on delete cascade,sort_order integer default 0,primary key(category_id,product_id));
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text unique,name text,phone text,address text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.reviews(id uuid primary key default gen_random_uuid(),product_id bigint references public.products(id) on delete cascade,profile_id uuid references public.profiles(id) on delete set null,reviewer_name text not null,rating integer not null check(rating between 1 and 5),body text not null,is_sample boolean default false,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),order_id text unique not null,user_id uuid references public.profiles(id) on delete set null,buyer_name text not null,phone text not null,address text not null,delivery_charges numeric(12,2) default 255,total_price numeric(12,2) not null,payment_method text not null check(payment_method in ('COD','PAID')),payment_status text not null default 'COD' check(payment_status in ('COD','in review','rejected','approved')),delivery_status text not null default 'in progress' check(delivery_status in ('in progress','in shipping','delivered','cancelled')),payment_tx_id text,payment_screenshot_url text,cancelled boolean default false,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid references public.orders(id) on delete cascade,product_id bigint references public.products(id) on delete set null,product_name text not null,product_price numeric(12,2) not null,quantity integer not null default 1);
create table if not exists public.admin_audit(id uuid primary key default gen_random_uuid(),action text,admin_email text,metadata jsonb,created_at timestamptz default now());

alter table public.products enable row level security; alter table public.categories enable row level security; alter table public.category_products enable row level security; alter table public.reviews enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.profiles enable row level security;
create policy "public products read" on public.products for select using (true); create policy "public categories read" on public.categories for select using (true); create policy "public category products read" on public.category_products for select using (true); create policy "public reviews read" on public.reviews for select using (true);
create policy "auth reviews insert" on public.reviews for insert to authenticated with check (true);
create policy "own profile" on public.profiles for all to authenticated using (auth.uid()=id) with check (auth.uid()=id);
create policy "own orders read" on public.orders for select to authenticated using (user_id=auth.uid()); create policy "own order insert" on public.orders for insert to authenticated with check (user_id=auth.uid());
create policy "own order items read" on public.order_items for select to authenticated using (exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
